USE WAREHOUSE COMPUTE_WH;
CREATE DATABASE IF NOT EXISTS GLOBO_RETAIL_DB;

USE DATABASE GLOBO_RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS CLEANSED;
CREATE SCHEMA IF NOT EXISTS STAR;
CREATE SCHEMA IF NOT EXISTS PRESENTATION;

SHOW SCHEMAS IN DATABASE GLOBO_RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS GLOBO_RETAIL_DB.EXTERNAL_STAGE;

CREATE OR REPLACE FILE FORMAT
    GLOBO_RETAIL_DB.EXTERNAL_STAGE.PARQUET_FILE_FORMAT
    TYPE = PARQUET
    USE_VECTORIZED_SCANNER = TRUE;


CREATE OR REPLACE STAGE GLOBO_RETAIL_DB.EXTERNAL_STAGE.AWS_STAGE
    URL = 's3://etl-and-data-warehouse/globo-retail-data-pipeline/processed-zone/'
    CREDENTIALS = (
    AWS_KEY_ID = '<YOUR_AWS_KEY_ID>'
    AWS_SECRET_KEY = '<YOUR_AWS_SECRET_KEY>'
        );

LIST @GLOBO_RETAIL_DB.EXTERNAL_STAGE.AWS_STAGE;
