SELECT COUNT(*)
FROM @AWS_STAGE;

CREATE OR REPLACE TABLE GLOBO_RETAIL_DB.CLEANSED.SALES_CLEAN (
    sales_id NUMBER(38,0) NOT NULL,
    product_id NUMBER(38,0) NOT NULL,
    timestamp TIMESTAMP_NTZ NOT NULL,
    region VARCHAR NOT NULL,
    quantity NUMBER(38,0) NOT NULL,
    price FLOAT NOT NULL,
    discount FLOAT NOT NULL,
    order_status VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    brand VARCHAR NOT NULL,
    rating FLOAT NOT NULL,
    in_stock BOOLEAN NOT NULL,
    launch_date TIMESTAMP_NTZ,
    gross_revenue FLOAT NOT NULL,
    discount_amount FLOAT NOT NULL,
    net_revenue FLOAT NOT NULL
);
DESC TABLE CLEANSED.SALES_CLEAN;

COPY INTO GLOBO_RETAIL_DB.CLEANSED.SALES_CLEAN
FROM @GLOBO_RETAIL_DB.EXTERNAL_STAGE.AWS_STAGE
FILE_FORMAT = (
    FORMAT_NAME = 'GLOBO_RETAIL_DB.EXTERNAL_STAGE.PARQUET_FILE_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = ABORT_STATEMENT;

SELECT COUNT(*) FROM GLOBO_RETAIL_DB.CLEANSED.SALES_CLEAN;

SELECT *
FROM GLOBO_RETAIL_DB.CLEANSED.SALES_CLEAN
LIMIT 10;